name: EerstePlugin
main: net.breecko.eersteplugin.Main
version: 1.0.0
author: Breecko
description: Epic Jump Plugin yay

commands:
    jump:
        usage: </jump>
        description: Teleports the player 10 blocks into the air
    fly:
        usage: </fly>
        description: Allows the player to fly
    spawn:
        usage: </spawn>
        description: Sends the player to Spawn
    afk:
        usage: </afk>
        description: Puts the player in AFK mode